import { Achievement } from '../models/Achievement';

export const ACHIEVEMENT_CATEGORIES = {
  STREAK: 'streak',
  SESSION_COUNT: 'session_count',
  TOTAL_TIME: 'total_time',
  EMOTION_MASTERY: 'emotion_mastery',
  EXERCISE_MASTERY: 'exercise_mastery',
  SPECIAL: 'special',
} as const;

export type AchievementCategory = typeof ACHIEVEMENT_CATEGORIES[keyof typeof ACHIEVEMENT_CATEGORIES];

export const ACHIEVEMENTS: Achievement[] = [
  // Streak Achievements
  {
    id: 'streak_3',
    title: 'Начало пути',
    description: 'Практикуйте 3 дня подряд',
    category: ACHIEVEMENT_CATEGORIES.STREAK,
    icon: '🔥',
    color: '#FF6B6B',
    condition: {
      type: 'streak',
      value: 3,
    },
    reward: {
      points: 50,
      badge: 'bronze',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'streak_7',
    title: 'Неделя силы',
    description: 'Практикуйте 7 дней подряд',
    category: ACHIEVEMENT_CATEGORIES.STREAK,
    icon: '⚡',
    color: '#FFD93D',
    condition: {
      type: 'streak',
      value: 7,
    },
    reward: {
      points: 100,
      badge: 'silver',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'streak_14',
    title: 'Две недели спокойствия',
    description: 'Практикуйте 14 дней подряд',
    category: ACHIEVEMENT_CATEGORIES.STREAK,
    icon: '🌟',
    color: '#6BCB77',
    condition: {
      type: 'streak',
      value: 14,
    },
    reward: {
      points: 200,
      badge: 'gold',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'streak_30',
    title: 'Месяц гармонии',
    description: 'Практикуйте 30 дней подряд',
    category: ACHIEVEMENT_CATEGORIES.STREAK,
    icon: '💎',
    color: '#4D96FF',
    condition: {
      type: 'streak',
      value: 30,
    },
    reward: {
      points: 500,
      badge: 'platinum',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'streak_60',
    title: 'Мастер постоянства',
    description: 'Практикуйте 60 дней подряд',
    category: ACHIEVEMENT_CATEGORIES.STREAK,
    icon: '👑',
    color: '#9D4EDD',
    condition: {
      type: 'streak',
      value: 60,
    },
    reward: {
      points: 1000,
      badge: 'diamond',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'streak_100',
    title: 'Легенда спокойствия',
    description: 'Практикуйте 100 дней подряд',
    category: ACHIEVEMENT_CATEGORIES.STREAK,
    icon: '🏆',
    color: '#FF006E',
    condition: {
      type: 'streak',
      value: 100,
    },
    reward: {
      points: 2000,
      badge: 'legendary',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },

  // Session Count Achievements
  {
    id: 'sessions_10',
    title: 'Первые шаги',
    description: 'Завершите 10 упражнений',
    category: ACHIEVEMENT_CATEGORIES.SESSION_COUNT,
    icon: '👣',
    color: '#A8DADC',
    condition: {
      type: 'session_count',
      value: 10,
    },
    reward: {
      points: 30,
      badge: 'bronze',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'sessions_50',
    title: 'Практикующий',
    description: 'Завершите 50 упражнений',
    category: ACHIEVEMENT_CATEGORIES.SESSION_COUNT,
    icon: '🎯',
    color: '#457B9D',
    condition: {
      type: 'session_count',
      value: 50,
    },
    reward: {
      points: 150,
      badge: 'silver',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'sessions_100',
    title: 'Сотня спокойствия',
    description: 'Завершите 100 упражнений',
    category: ACHIEVEMENT_CATEGORIES.SESSION_COUNT,
    icon: '💯',
    color: '#1D3557',
    condition: {
      type: 'session_count',
      value: 100,
    },
    reward: {
      points: 300,
      badge: 'gold',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'sessions_250',
    title: 'Эксперт осознанности',
    description: 'Завершите 250 упражнений',
    category: ACHIEVEMENT_CATEGORIES.SESSION_COUNT,
    icon: '🧘',
    color: '#E63946',
    condition: {
      type: 'session_count',
      value: 250,
    },
    reward: {
      points: 750,
      badge: 'platinum',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'sessions_500',
    title: 'Гуру медитации',
    description: 'Завершите 500 упражнений',
    category: ACHIEVEMENT_CATEGORIES.SESSION_COUNT,
    icon: '🕉️',
    color: '#F77F00',
    condition: {
      type: 'session_count',
      value: 500,
    },
    reward: {
      points: 1500,
      badge: 'diamond',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },

  // Total Time Achievements
  {
    id: 'time_60',
    title: 'Час спокойствия',
    description: 'Практикуйте в общей сложности 1 час',
    category: ACHIEVEMENT_CATEGORIES.TOTAL_TIME,
    icon: '⏰',
    color: '#06FFA5',
    condition: {
      type: 'total_time',
      value: 60,
    },
    reward: {
      points: 40,
      badge: 'bronze',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'time_300',
    title: 'Пять часов мира',
    description: 'Практикуйте в общей сложности 5 часов',
    category: ACHIEVEMENT_CATEGORIES.TOTAL_TIME,
    icon: '🕐',
    color: '#FFFB46',
    condition: {
      type: 'total_time',
      value: 300,
    },
    reward: {
      points: 120,
      badge: 'silver',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'time_600',
    title: 'Десять часов гармонии',
    description: 'Практикуйте в общей сложности 10 часов',
    category: ACHIEVEMENT_CATEGORIES.TOTAL_TIME,
    icon: '🕙',
    color: '#B4E7CE',
    condition: {
      type: 'total_time',
      value: 600,
    },
    reward: {
      points: 250,
      badge: 'gold',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'time_1200',
    title: 'Двадцать часов дзен',
    description: 'Практикуйте в общей сложности 20 часов',
    category: ACHIEVEMENT_CATEGORIES.TOTAL_TIME,
    icon: '🌙',
    color: '#FFE5E5',
    condition: {
      type: 'total_time',
      value: 1200,
    },
    reward: {
      points: 500,
      badge: 'platinum',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'time_3000',
    title: 'Пятьдесят часов просветления',
    description: 'Практикуйте в общей сложности 50 часов',
    category: ACHIEVEMENT_CATEGORIES.TOTAL_TIME,
    icon: '☀️',
    color: '#FFC300',
    condition: {
      type: 'total_time',
      value: 3000,
    },
    reward: {
      points: 1200,
      badge: 'diamond',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },

  // Emotion Mastery Achievements
  {
    id: 'stress_master',
    title: 'Укротитель стресса',
    description: 'Завершите 20 упражнений для стресса',
    category: ACHIEVEMENT_CATEGORIES.EMOTION_MASTERY,
    icon: '😌',
    color: '#FF6B9D',
    condition: {
      type: 'emotion_sessions',
      emotion: 'stress',
      value: 20,
    },
    reward: {
      points: 200,
      badge: 'gold',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'anxiety_master',
    title: 'Победитель тревоги',
    description: 'Завершите 20 упражнений для беспокойства',
    category: ACHIEVEMENT_CATEGORIES.EMOTION_MASTERY,
    icon: '🦋',
    color: '#C77DFF',
    condition: {
      type: 'emotion_sessions',
      emotion: 'anxiety',
      value: 20,
    },
    reward: {
      points: 200,
      badge: 'gold',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'sadness_master',
    title: 'Хранитель радости',
    description: 'Завершите 20 упражнений для грусти',
    category: ACHIEVEMENT_CATEGORIES.EMOTION_MASTERY,
    icon: '🌈',
    color: '#7209B7',
    condition: {
      type: 'emotion_sessions',
      emotion: 'sadness',
      value: 20,
    },
    reward: {
      points: 200,
      badge: 'gold',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'fatigue_master',
    title: 'Источник энергии',
    description: 'Завершите 20 упражнений для усталости',
    category: ACHIEVEMENT_CATEGORIES.EMOTION_MASTERY,
    icon: '⚡',
    color: '#3A0CA3',
    condition: {
      type: 'emotion_sessions',
      emotion: 'fatigue',
      value: 20,
    },
    reward: {
      points: 200,
      badge: 'gold',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'all_emotions_master',
    title: 'Мастер эмоций',
    description: 'Завершите по 20 упражнений для каждой эмоции',
    category: ACHIEVEMENT_CATEGORIES.EMOTION_MASTERY,
    icon: '🎭',
    color: '#F72585',
    condition: {
      type: 'all_emotions',
      value: 20,
    },
    reward: {
      points: 1000,
      badge: 'legendary',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },

  // Exercise Mastery Achievements
  {
    id: 'breathing_master',
    title: 'Мастер дыхания',
    description: 'Завершите 30 дыхательных упражнений',
    category: ACHIEVEMENT_CATEGORIES.EXERCISE_MASTERY,
    icon: '🌬️',
    color: '#4CC9F0',
    condition: {
      type: 'exercise_type_sessions',
      exerciseType: 'breathing',
      value: 30,
    },
    reward: {
      points: 250,
      badge: 'platinum',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'meditation_master',
    title: 'Мастер медитации',
    description: 'Завершите 30 медитаций',
    category: ACHIEVEMENT_CATEGORIES.EXERCISE_MASTERY,
    icon: '🧘‍♀️',
    color: '#4895EF',
    condition: {
      type: 'exercise_type_sessions',
      exerciseType: 'meditation',
      value: 30,
    },
    reward: {
      points: 250,
      badge: 'platinum',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'mindfulness_master',
    title: 'Мастер осознанности',
    description: 'Завершите 30 практик внимательности',
    category: ACHIEVEMENT_CATEGORIES.EXERCISE_MASTERY,
    icon: '🌸',
    color: '#4361EE',
    condition: {
      type: 'exercise_type_sessions',
      exerciseType: 'mindfulness',
      value: 30,
    },
    reward: {
      points: 250,
      badge: 'platinum',
    },
    unlocked: false,
    progress: 0,
    unlockedAt: null,
  },
  {
    id: 'all_exercises_master',
    title: 'Универсальный мастер',
    description: 'Завершите по 30 упражнений каждого типа',
    category: ACHIEVEMENT_CATEGORIES.EXERCISE_