export interface Emotion {
  id: string;
  name: string;
  icon: string;
  color: string;
  darkColor: string;
  gradient: [string, string];
  description: string;
  intensity: 'low' | 'medium' | 'high';
  category: 'negative' | 'neutral' | 'positive';
  keywords: string[];
  relatedEmotions: string[];
  recommendedExercises: string[];
}

export const EMOTIONS: Record<string, Emotion> = {
  sadness: {
    id: 'sadness',
    name: 'Грусть',
    icon: '😔',
    color: '#6B7FD7',
    darkColor: '#4A5FB5',
    gradient: ['#6B7FD7', '#4A5FB5'],
    description: 'Чувство печали, тоски или уныния',
    intensity: 'medium',
    category: 'negative',
    keywords: ['печаль', 'тоска', 'уныние', 'подавленность', 'меланхолия'],
    relatedEmotions: ['loneliness', 'grief', 'disappointment'],
    recommendedExercises: ['calm-meditation', 'body-scan', 'gratitude-practice', 'gentle-breathing'],
  },
  stress: {
    id: 'stress',
    name: 'Стресс',
    icon: '😰',
    color: '#E74C3C',
    darkColor: '#C0392B',
    gradient: ['#E74C3C', '#C0392B'],
    description: 'Напряжение, перегрузка, давление',
    intensity: 'high',
    category: 'negative',
    keywords: ['напряжение', 'перегрузка', 'давление', 'беспокойство', 'тревога'],
    relatedEmotions: ['anxiety', 'overwhelm', 'tension'],
    recommendedExercises: ['box-breathing', 'progressive-relaxation', '4-7-8-breathing', 'stress-relief-meditation'],
  },
  anxiety: {
    id: 'anxiety',
    name: 'Беспокойство',
    icon: '😟',
    color: '#F39C12',
    darkColor: '#D68910',
    gradient: ['#F39C12', '#D68910'],
    description: 'Тревога, волнение, беспокойство о будущем',
    intensity: 'high',
    category: 'negative',
    keywords: ['тревога', 'волнение', 'беспокойство', 'страх', 'нервозность'],
    relatedEmotions: ['stress', 'fear', 'worry'],
    recommendedExercises: ['grounding-5-4-3-2-1', 'calm-meditation', 'mindful-breathing', 'anxiety-relief'],
  },
  fatigue: {
    id: 'fatigue',
    name: 'Усталость',
    icon: '😴',
    color: '#95A5A6',
    darkColor: '#7F8C8D',
    gradient: ['#95A5A6', '#7F8C8D'],
    description: 'Физическое или эмоциональное истощение',
    intensity: 'medium',
    category: 'negative',
    keywords: ['усталость', 'истощение', 'утомление', 'слабость', 'вялость'],
    relatedEmotions: ['burnout', 'exhaustion', 'lethargy'],
    recommendedExercises: ['body-scan', 'restorative-meditation', 'gentle-breathing', 'energy-boost'],
  },
  anger: {
    id: 'anger',
    name: 'Гнев',
    icon: '😠',
    color: '#E84118',
    darkColor: '#C23616',
    gradient: ['#E84118', '#C23616'],
    description: 'Раздражение, злость, негодование',
    intensity: 'high',
    category: 'negative',
    keywords: ['гнев', 'злость', 'раздражение', 'ярость', 'негодование'],
    relatedEmotions: ['frustration', 'irritation', 'rage'],
    recommendedExercises: ['cooling-breath', 'anger-release', 'mindful-walking', 'progressive-relaxation'],
  },
  loneliness: {
    id: 'loneliness',
    name: 'Одиночество',
    icon: '😞',
    color: '#8E44AD',
    darkColor: '#6C3483',
    gradient: ['#8E44AD', '#6C3483'],
    description: 'Чувство изоляции и отсутствия связи',
    intensity: 'medium',
    category: 'negative',
    keywords: ['одиночество', 'изоляция', 'покинутость', 'отчуждение'],
    relatedEmotions: ['sadness', 'isolation', 'emptiness'],
    recommendedExercises: ['loving-kindness', 'connection-meditation', 'gratitude-practice', 'self-compassion'],
  },
  overwhelm: {
    id: 'overwhelm',
    name: 'Перегрузка',
    icon: '🤯',
    color: '#E67E22',
    darkColor: '#CA6F1E',
    gradient: ['#E67E22', '#CA6F1E'],
    description: 'Чувство подавленности количеством задач',
    intensity: 'high',
    category: 'negative',
    keywords: ['перегрузка', 'завал', 'подавленность', 'переполненность'],
    relatedEmotions: ['stress', 'anxiety', 'confusion'],
    recommendedExercises: ['grounding-5-4-3-2-1', 'box-breathing', 'priority-meditation', 'mindful-pause'],
  },
  frustration: {
    id: 'frustration',
    name: 'Фрустрация',
    icon: '😤',
    color: '#E67E22',
    darkColor: '#D35400',
    gradient: ['#E67E22', '#D35400'],
    description: 'Разочарование от препятствий и неудач',
    intensity: 'medium',
    category: 'negative',
    keywords: ['фрустрация', 'разочарование', 'досада', 'недовольство'],
    relatedEmotions: ['anger', 'disappointment', 'irritation'],
    recommendedExercises: ['acceptance-meditation', 'cooling-breath', 'perspective-shift', 'letting-go'],
  },
  fear: {
    id: 'fear',
    name: 'Страх',
    icon: '😨',
    color: '#34495E',
    darkColor: '#2C3E50',
    gradient: ['#34495E', '#2C3E50'],
    description: 'Тревога перед угрозой или опасностью',
    intensity: 'high',
    category: 'negative',
    keywords: ['страх', 'испуг', 'ужас', 'боязнь', 'паника'],
    relatedEmotions: ['anxiety', 'panic', 'terror'],
    recommendedExercises: ['grounding-5-4-3-2-1', 'safe-place-visualization', 'calm-meditation', 'courage-building'],
  },
  guilt: {
    id: 'guilt',
    name: 'Вина',
    icon: '😔',
    color: '#7D3C98',
    darkColor: '#5B2C6F',
    gradient: ['#7D3C98', '#5B2C6F'],
    description: 'Чувство вины или угрызения совести',
    intensity: 'medium',
    category: 'negative',
    keywords: ['вина', 'стыд', 'угрызения', 'раскаяние', 'сожаление'],
    relatedEmotions: ['shame', 'regret', 'remorse'],
    recommendedExercises: ['self-compassion', 'forgiveness-meditation', 'loving-kindness', 'acceptance-practice'],
  },
  confusion: {
    id: 'confusion',
    name: 'Растерянность',
    icon: '😕',
    color: '#95A5A6',
    darkColor: '#7F8C8D',
    gradient: ['#95A5A6', '#7F8C8D'],
    description: 'Неопределенность, замешательство',
    intensity: 'low',
    category: 'neutral',
    keywords: ['растерянность', 'замешательство', 'неопределенность', 'сомнение'],
    relatedEmotions: ['uncertainty', 'doubt', 'bewilderment'],
    recommendedExercises: ['clarity-meditation', 'mindful-breathing', 'body-scan', 'grounding-5-4-3-2-1'],
  },
  boredom: {
    id: 'boredom',
    name: 'Скука',
    icon: '😐',
    color: '#BDC3C7',
    darkColor: '#95A5A6',
    gradient: ['#BDC3C7', '#95A5A6'],
    description: 'Отсутствие интереса или стимуляции',
    intensity: 'low',
    category: 'neutral',
    keywords: ['скука', 'апатия', 'безразличие', 'монотонность'],
    relatedEmotions: ['apathy', 'disinterest', 'monotony'],
    recommendedExercises: ['curiosity-practice', 'mindful-observation', 'energy-boost', 'creative-visualization'],
  },
  calm: {
    id: 'calm',
    name: 'Спокойствие',
    icon: '😌',
    color: '#3498DB',
    darkColor: '#2980B9',
    gradient: ['#3498DB', '#2980B9'],
    description: 'Умиротворение и внутренний покой',
    intensity: 'low',
    category: 'positive',
    keywords: ['спокойствие', 'умиротворение', 'покой', 'безмятежность'],
    relatedEmotions: ['peace', 'serenity', 'tranquility'],
    recommendedExercises: ['mindful-breathing', 'calm-meditation', 'body-scan', 'peaceful-visualization'],
  },
  joy: {
    id: 'joy',
    name: 'Радость',
    icon: '😊',
    color: '#F1C40F',
    darkColor: '#F39C12',
    gradient: ['#F1C40F', '#F39C12'],
    description: 'Счастье, радость, удовольствие',
    intensity: 'medium',
    category: 'positive',
    keywords: ['радость', 'счастье', 'удовольствие', 'веселье', 'восторг'],
    relatedEmotions: ['happiness', 'delight', 'pleasure'],
    recommendedExercises: ['gratitude-practice', 'joy-amplification', 'loving-kindness', 'celebration-meditation'],
  },
  gratitude: {
    id: 'gratitude',
    name: 'Благодарность',
    icon: '🙏',
    color: '#27AE60',
    darkColor: '#229954',
    gradient: ['#27AE60', '#229954'],
    description: 'Признательность и благодарность',
    intensity: 'low',
    category: 'positive',
    keywords: ['благодарность', 'признательность', 'ценность', 'appreciation'],
    relatedEmotions: ['appreciation', 'thankfulness', 'contentment'],
    recommendedExercises: ['gratitude-practice', 'loving-kindness', 'appreciation-meditation', 'mindful-savoring'],
  },
  hope: {
    id: 'hope',
    name: 'Надежда',
    icon: '🌟',
    color: '#1ABC9C',
    darkColor: '#16A085',
    gradient: ['#1ABC9C', '#16A085'],
    description: 'Оптимизм и вера в лучшее',
    intensity: 'medium',
    category: 'positive',
    keywords: ['надежда', 'оптимизм', 'вера', 'ожидание', 'предвкушение'],
    relatedEmotions: ['optimism', 'anticipation', 'faith'],
    recommendedExercises: ['future-visualization', 'hope-building', 'positive-affirmations', 'gratitude-practice'],
  },
  confidence: {
    id: 'confidence',
    name: 'Уверенность',
    icon: '💪',
    color: '#E74C3C',
    darkColor: '#C0392B',
    gradient: ['#E74C3C', '#C0392B'],
    description: 'Вера в себя и свои способности',
    intensity: 'medium',
    category: 'positive',
    keywords: ['уверенность', 'вера', 'сила', 'решительность', 'смелость'],
    relatedEmotions: ['courage', 'determination', 'strength'],
    recommendedExercises: ['confidence-building', 'power-pose-meditation', 'achievement-visualization', 'self-affirmation'],
  },
  love: {
    id: 'love',
    name: 'Любовь',
    icon: '❤️',
    color: '#E91E63',
    darkColor: '#C2185B',
    gradient: ['#E91E63', '#C2185B'],
    description: 'Глубокая привязанность и забота',
    intensity: 'high',
    category: 'positive',
    keywords: ['любовь', 'привязанность', 'забота', 'нежность', 'тепло'],
    relatedEmotions: ['affection', 'tenderness', 'warmth'],
    recommendedExercises: ['loving-kindness', 'heart-opening', 'compassion-meditation', 'connection-practice'],
  },
  excitement: {
    id: 'excitement',
    name: 'Волнение',
    icon: '🤩',
    color: '#FF6B6B',
    darkColor: '#EE5A52',
    gradient: ['#FF6B6B', '#EE5A52'],
    description: 'Приподнятое настроение и энтузиазм',
    intensity: 'high',
    category: 'positive',
    keywords: ['волнение', 'энтузиазм', 'возбуждение', 'азарт', 'восторг'],
    relatedEmotions: ['enthusiasm', 'thrill', 'exhilaration'],
    recommendedExercises: ['energy-channeling', 'excitement-grounding', 'focused-breathing', 'mindful-presence'],
  },
  contentment: {
    id: 'contentment',
    name: 'Удовлетворенность',
    icon: '😊',
    color: '#52C41A',
    darkColor: '#389E0D',
    gradient: ['#52C41A', '#389E0D'],
    description: 'Чувство удовлетворения и полноты',
    intensity: 'low',
    category: 'positive',
    keywords: ['удовлетворенность', 'дов